spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/SamyMartins98/ms-course-configs
          username: ${GITHUB_USER}
          password: ${GITHUB_TOKEN}

server:
  port: 8888
